src/c/sopt_l1.c File Reference
sopt_l1.c File Reference
#include "sopt_config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <complex.h>
#include <math.h>
#include "sopt_utility.h"
#include "sopt_error.h"
#include "sopt_l1.h"
Macros
#define min(a, b) (a<b?a:b)
#define max(a, b) (a<b?b:a)
Functions
void sopt_l1_solver (void *xsol, int nx, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, void(*Psi)(void *out, void *in, void **data), void **Psi_data, void(*Psit)(void *out, void *in, void **data), void **Psit_data, int nr, void *y, int ny, double *weights, sopt_l1_param param)
void sopt_l1_rwmin (void *xsol, int nx, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, void(*Psi)(void *out, void *in, void **data), void **Psi_data, void(*Psit)(void *out, void *in, void **data), void **Psit_data, int nr, void *y, int ny, sopt_l1_param paraml1, sopt_l1_rwparam paramrwl1)
void sopt_l1_sdmm (void *xsol, int nx, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, void(*Psi)(void *out, void *in, void **data), void **Psi_data, void(*Psit)(void *out, void *in, void **data), void **Psit_data, int nr, void *y, int ny, double *weights, sopt_l1_sdmmparam param)
void sopt_l1_rwsdmm (void *xsol, int nx, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, void(*Psi)(void *out, void *in, void **data), void **Psi_data, void(*Psit)(void *out, void *in, void **data), void **Psit_data, int nr, void *y, int ny, sopt_l1_sdmmparam paraml1, sopt_l1_rwparam paramrwl1)
void sopt_l1_solver_aadmm (void *xsol, int nx, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, void(*Psi)(void *out, void *in, void **data), void **Psi_data, void(*Psit)(void *out, void *in, void **data), void **Psit_data, int nr, void *y, int ny, double *weights, sopt_l1_param param)
Macro Definition Documentation
#define max (a, b) (a<b?b:a)
Definition at line 15 of file sopt_l1.c.
Referenced by sopt_l1_rwmin(), and sopt_l1_rwsdmm().
#define min (a, b) (a<b?a:b)
Definition at line 14 of file sopt_l1.c.
Referenced by sopt_l1_sdmm(), and sopt_l1_solver_aadmm().
Function Documentation
void sopt_l1_rwmin (void * xsol, int nx, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, void(*)(void *out, void *in, void **data) Psi, void ** Psi_data, void(*)(void *out, void *in, void **data) Psit, void ** Psit_data, int nr, void * y, int ny, sopt_l1_param paraml1, sopt_l1_rwparam paramrwl1)
Reweighted L1 minimization function that uses an homotopy continuation method to approximate the L0 norm. It solves at each iteration the following problem::
where is the sparsifying operator, is the diagonal weight matrix, is the measurement operator, is a noise tolerance, is the measurement vector and is a diagonal weight matrix that changes at every iteration. The solution is denoted .
Note
The solver can be used to solve the analysis based problem, as written, or the synthesis based problem by mapping and , where is the identity matrix.
Parameters
[in,out] xsol Solution (). It stores the initial solution, which should be set as an input to the function, and it is modified when the finall solution is found.
[in] nx Dimension of the signal ().
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to measurement operator .
[in] At Pointer to the adjoint of the measurement operator .
[in] At_data Data structure associated to the adjoint of the measurement operator .
[in] Psi Pointer to the synthesis sparsity operator .
[in] Psi_data Data structure associated to the synthesis sparsity operator .
[in] Psit Pointer to the analysis sparsity operator .
[in] Psit_data Data structure associated to the analysis sparisty operator .
[in] nr Dimension of the signal in the representation domain ().
[in] y Measurement vector ().
[in] ny Dimension of measurement vector, i.e. number of measurements ().
[in] paraml1 Data structure with the parameters for the L1 solver (including).
[in] paramrwl1 Data structure with the parameters for the reweighted L1 solver.
Definition at line 366 of file sopt_l1.c.
References sopt_l1_rwparam::init_sol, max, sopt_l1_rwparam::max_iter, sopt_l1_param::real_out, sopt_l1_rwparam::rel_var, sopt_l1_rwparam::sigma, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_l1_solver(), and sopt_l1_rwparam::verbose.
Referenced by main().
void sopt_l1_rwsdmm (void * xsol, int nx, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, void(*)(void *out, void *in, void **data) Psi, void ** Psi_data, void(*)(void *out, void *in, void **data) Psit, void ** Psit_data, int nr, void * y, int ny, sopt_l1_sdmmparam paraml1, sopt_l1_rwparam paramrwl1)
Reweighted L1 minimization function that uses an homotopy continuation method to approximate the L0 norm. It solves at each iteration the following problem::
where is the sparsifying operator, is the diagonal weight matrix, is the measurement operator, is a noise tolerance, is the measurement vector and is a diagonal weight matrix that changes at every iteration. The solution is denoted . The Simultaneous Direction Method of Multipliers (SDMM) is used to solve the optimization problem.
Note
The solver can be used to solve the analysis based problem, as written, or the synthesis based problem by mapping and , where is the identity matrix.
Parameters
[in,out] xsol Solution (). It stores the initial solution, which should be set as an input to the function, and it is modified when the finall solution is found.
[in] nx Dimension of the signal ().
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to measurement operator .
[in] At Pointer to the adjoint of the measurement operator .
[in] At_data Data structure associated to the adjoint of the measurement operator .
[in] Psi Pointer to the synthesis sparsity operator .
[in] Psi_data Data structure associated to the synthesis sparsity operator .
[in] Psit Pointer to the analysis sparsity operator .
[in] Psit_data Data structure associated to the analysis sparisty operator .
[in] nr Dimension of the signal in the representation domain ().
[in] y Measurement vector ().
[in] ny Dimension of measurement vector, i.e. number of measurements ().
[in] paraml1 Data structure with the parameters for the L1 solver (including).
[in] paramrwl1 Data structure with the parameters for the reweighted L1 solver.
Definition at line 1054 of file sopt_l1.c.
References sopt_l1_rwparam::init_sol, max, sopt_l1_rwparam::max_iter, sopt_l1_sdmmparam::real_data, sopt_l1_rwparam::rel_var, sopt_l1_rwparam::sigma, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_l1_sdmm(), sopt_utility_projposc(), sopt_utility_projposr(), and sopt_l1_rwparam::verbose.
void sopt_l1_sdmm (void * xsol, int nx, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, void(*)(void *out, void *in, void **data) Psi, void ** Psi_data, void(*)(void *out, void *in, void **data) Psit, void ** Psit_data, int nr, void * y, int ny, double * weights, sopt_l1_sdmmparam param)
This function solves the problem:
where is the sparsifying operator, is the diagonal weight matrix, is the measurement operator, is a noise tolerance and is the measurement vector. The solution is denoted . The Simultaneous Direction Method of Multipliers (SDMM) is used to solve the optimization problem.
Note
The solver can be used to solve the analysis based problem, as written, or the synthesis based problem by mapping and , where is the identity matrix.
Parameters
[in,out] xsol Solution (). It stores the initial solution, which should be set as an input to the function, and it is modified when the finall solution is found.
[in] nx Dimension of the signal ().
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to measurement operator .
[in] At Pointer to the adjoint of the measurement operator .
[in] At_data Data structure associated to the adjoint of the measurement operator .
[in] Psi Pointer to the synthesis sparsity operator .
[in] Psi_data Data structure associated to the synthesis sparsity operator .
[in] Psit Pointer to the analysis sparsity operator .
[in] Psit_data Data structure associated to the analysis sparisty operator .
[in] nr Dimension of the signal in the representation domain ().
[in] y Measurement vector ().
[in] ny Dimension of measurement vector, i.e. number of measurements ().
[in] weights Weights for the weighted L1 problem. Vector storing the main diagonal of .
[in] param Data structure with the parameters of the optimization (including).
Definition at line 596 of file sopt_l1.c.
References sopt_l1_sdmmparam::cg_max_iter, sopt_l1_sdmmparam::cg_tol, sopt_l1_sdmmparam::epsilon, sopt_l1_sdmmparam::epsilon_tol, sopt_l1_sdmmparam::gamma, sopt_l1_sdmmparam::max_iter, min, sopt_l1_sdmmparam::real_data, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_utility_cgsolc(), sopt_utility_cgsolr(), sopt_utility_l1normc(), sopt_utility_l1normr(), sopt_utility_projposc(), sopt_utility_projposr(), sopt_utility_softthc(), sopt_utility_softthr(), and sopt_l1_sdmmparam::verbose.
Referenced by sopt_l1_rwsdmm().
void sopt_l1_solver (void * xsol, int nx, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, void(*)(void *out, void *in, void **data) Psi, void ** Psi_data, void(*)(void *out, void *in, void **data) Psit, void ** Psit_data, int nr, void * y, int ny, double * weights, sopt_l1_param param)
This function solves the problem:
where is the sparsifying operator, is the diagonal weight matrix, is the measurement operator, is a noise tolerance and is the measurement vector. The solution is denoted .
Note
The solver can be used to solve the analysis based problem, as written, or the synthesis based problem by mapping and , where is the identity matrix.
Parameters
[in,out] xsol Solution (). It stores the initial solution, which should be set as an input to the function, and it is modified when the finall solution is found.
[in] nx Dimension of the signal ().
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to measurement operator .
[in] At Pointer to the adjoint of the measurement operator .
[in] At_data Data structure associated to the adjoint of the measurement operator .
[in] Psi Pointer to the synthesis sparsity operator .
[in] Psi_data Data structure associated to the synthesis sparsity operator .
[in] Psit Pointer to the analysis sparsity operator .
[in] Psit_data Data structure associated to the analysis sparisty operator .
[in] nr Dimension of the signal in the representation domain ().
[in] y Measurement vector ().
[in] ny Dimension of measurement vector, i.e. number of measurements ().
[in] weights Weights for the weighted L1 problem. Vector storing the main diagonal of .
[in] param Data structure with the parameters of the optimization (including).
Definition at line 63 of file sopt_l1.c.
References sopt_l1_param::epsilon, sopt_l1_param::gamma, sopt_l1_param::max_iter, sopt_l1_param::paraml1, sopt_l1_param::paraml2b, sopt_l1_param::real_meas, sopt_l1_param::real_out, sopt_l1_param::rel_obj, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_prox_l1(), sopt_prox_l2b(), sopt_utility_l1normc(), sopt_utility_l1normr(), and sopt_l1_param::verbose.
Referenced by main(), and sopt_l1_rwmin().
void sopt_l1_solver_aadmm (void * xsol, int nx, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, void(*)(void *out, void *in, void **data) Psi, void ** Psi_data, void(*)(void *out, void *in, void **data) Psit, void ** Psit_data, int nr, void * y, int ny, double * weights, sopt_l1_param param)
This function solves the problem:
where is the sparsifying operator, is the diagonal weight matrix, is the measurement operator, is a noise tolerance and is the measurement vector. The solution is denoted . The Approximate Alternating Direction Method of Multipliers (AADMM) is used to solve the optimization problem.
Note
The solver can be used to solve the analysis based problem, as written, or the synthesis based problem by mapping and , where is the identity matrix.
Parameters
[in,out] xsol Solution (). It stores the initial solution, which should be set as an input to the function, and it is modified when the finall solution is found.
[in] nx Dimension of the signal ().
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to measurement operator .
[in] At Pointer to the adjoint of the measurement operator .
[in] At_data Data structure associated to the adjoint of the measurement operator .
[in] Psi Pointer to the synthesis sparsity operator .
[in] Psi_data Data structure associated to the synthesis sparsity operator .
[in] Psit Pointer to the analysis sparsity operator .
[in] Psit_data Data structure associated to the analysis sparisty operator .
[in] nr Dimension of the signal in the representation domain ().
[in] y Measurement vector ().
[in] ny Dimension of measurement vector, i.e. number of measurements ().
[in] weights Weights for the weighted L1 problem. Vector storing the main diagonal of .
[in] param Data structure with the parameters of the optimization (including).
Definition at line 1300 of file sopt_l1.c.
References sopt_l1_param::epsilon, sopt_l1_param::gamma, sopt_l1_param::max_iter, min, sopt_prox_l1param::nu, sopt_l1_param::paraml1, sopt_l1_param::real_out, sopt_l1_param::rel_obj, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_prox_l1(), sopt_utility_l1normr(), and sopt_l1_param::verbose.