src/c/sopt_meas.c File Reference
sopt_meas.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <cblas.h>
#include "sopt_ran.h"
#include "sopt_error.h"
#include "sopt_sparsemat.h"
#include "sopt_meas.h"
Functions
void sopt_meas_urandsamp (void *out, void *in, void **data)
void sopt_meas_urandsampadj (void *out, void *in, void **data)
void sopt_meas_identity (void *out, void *in, void **data)
void sopt_meas_densematc (void *out, void *in, void **data)
void sopt_meas_densematadjc (void *out, void *in, void **data)
void sopt_meas_densematr (void *out, void *in, void **data)
void sopt_meas_densematadjr (void *out, void *in, void **data)
void sopt_meas_sparsematc (void *out, void *in, void **data)
void sopt_meas_sparsematadjc (void *out, void *in, void **data)
void sopt_meas_sparsematr (void *out, void *in, void **data)
void sopt_meas_sparsematadjr (void *out, void *in, void **data)
Function Documentation
void sopt_meas_densematadjc (void * out, void * in, void ** data)
Complex dense matrix measurement adjoint operator.
Parameters:
[out] out Output vector of dimension nx.
[in] in Input vector of dimension nmeas.
[in] data Data structure with the information of the sampling process.
Definition at line 176 of file sopt_meas.c.
References sopt_meas_dcmatparam::mat, sopt_meas_dcmatparam::nmeas, and sopt_meas_dcmatparam::nx.
void sopt_meas_densematadjr (void * out, void * in, void ** data)
Real dense matrix measurement adjoint operator.
Parameters:
[out] out Output vector of dimension nx.
[in] in Input vector of dimension nmeas.
[in] data Data structure with the information of the sampling process.
Definition at line 231 of file sopt_meas.c.
References sopt_meas_drmatparam::mat, sopt_meas_drmatparam::nmeas, and sopt_meas_drmatparam::nx.
void sopt_meas_densematc (void * out, void * in, void ** data)
Complex dense matrix measurement operator. Takes nmeas measurements of the vector x of dimension nx.
Parameters:
[out] out Output vector of dimension nmeas.
[in] in Input vector of dimension nx.
[in] data Data structure with the information of the sampling process.
Definition at line 146 of file sopt_meas.c.
References sopt_meas_dcmatparam::mat, sopt_meas_dcmatparam::nmeas, and sopt_meas_dcmatparam::nx.
void sopt_meas_densematr (void * out, void * in, void ** data)
Real dense matrix measurement operator. Takes nmeas measurements of the vector x of dimension nx.
Parameters:
[out] out Output vector of dimension nmeas.
[in] in Input vector of dimension nx.
[in] data Data structure with the information of the sampling process.
Definition at line 207 of file sopt_meas.c.
References sopt_meas_drmatparam::mat, sopt_meas_drmatparam::nmeas, and sopt_meas_drmatparam::nx.
void sopt_meas_identity (void * out, void * in, void ** data)
Identity operator. Adjoint same as forward.
Parameters:
[out] out Output vector of dimension nx.
[in] in Input vector of dimension nx.
[in] data Data structure with the information of the sampling process. data[0] nx dimension of the array. data[1] real_flag reality flag. 1 for real data, 0 for complex.
Definition at line 121 of file sopt_meas.c.
void sopt_meas_sparsematadjc (void * out, void * in, void ** data)
Complex sparse matrix measurement adjoint operator.
Parameters:
[out] out Output vector of dimension nx.
[in] in Input vector of dimension nmeas.
[in] data Data structure with the information of the sampling process.
Definition at line 277 of file sopt_meas.c.
References sopt_sparsemat_adj_complex().
void sopt_meas_sparsematadjr (void * out, void * in, void ** data)
Complex sparse matrix measurement adjoint operator.
Parameters:
[out] out Output vector of dimension nx.
[in] in Input vector of dimension nmeas.
[in] data Data structure with the information of the sampling process.
Definition at line 318 of file sopt_meas.c.
References sopt_sparsemat_adj_real().
void sopt_meas_sparsematc (void * out, void * in, void ** data)
Complex sparse matrix measurement operator. Takes nmeas measurements of the vector x of dimension nx.
Parameters:
[out] out Output vector of dimension nmeas.
[in] in Input vector of dimension nx.
[in] data Data structure with the information of the sampling process. data[0] real_flag. Reality flag. 1 real data, 0 complex data. data[1] structure containing the sparse matrix info
Definition at line 257 of file sopt_meas.c.
References sopt_sparsemat_fwd_complex().
void sopt_meas_sparsematr (void * out, void * in, void ** data)
Complex sparse matrix measurement operator. Takes nmeas measurements of the vector x of dimension nx.
Parameters:
[out] out Output vector of dimension nmeas.
[in] in Input vector of dimension nx.
[in] data Data structure with the information of the sampling process.
Definition at line 298 of file sopt_meas.c.
References sopt_sparsemat_fwd_real().
void sopt_meas_urandsamp (void * out, void * in, void ** data)
Random uniform sampling. Takes nmeas samples uniformly at random from the vector x of dimension nx.
Parameters:
[out] out Output vector of dimension nmeas.
[in] in Input vector of dimension nx.
[in] data Data structure with the information of the sampling process.
Definition at line 37 of file sopt_meas.c.
References sopt_meas_usparam::nmeas, sopt_meas_usparam::perm, and sopt_meas_usparam::real_flag.
Referenced by main().
void sopt_meas_urandsampadj (void * out, void * in, void ** data)
Random uniform sampling. Adjoint opeartor.
Parameters:
[out] out Output vector of dimension nx.
[in] in Input vector of dimension nmeas.
[in] data Data structure with the information of the sampling process.
Definition at line 76 of file sopt_meas.c.
References sopt_meas_usparam::nmeas, sopt_meas_usparam::nx, sopt_meas_usparam::perm, and sopt_meas_usparam::real_flag.
Referenced by main().