src/c/sopt_image.c File Reference
sopt_image.c File Reference
#include "sopt_config.h"
#include <stdlib.h>
#include <tiffio.h>
#include "sopt_error.h"
Functions
int spot_image_tiff_read (double **img, int *nx, int *ny, char *filename, double scale, double offset)
int spot_image_tiff_write (double *img, int nx, int ny, char *filename, double scale, double offset)
Detailed Description
Functionality to read and write image files.
Definition in file sopt_image.c.
Function Documentation
int spot_image_tiff_read (double ** img, int * nx, int * ny, char * filename, double scale, double offset)
Read RGBA tiff image from file as greyscale image (the red channel of the RGBA image is read).
Note
Memory for img is allocated herein and must be freed by the calling routine.
Parameters
[out] img Greyscale image read from tiff file.
[out] nx Dimension of image in x direction.
[out] ny Dimension of image in y direction.
[in] filename Name of file to read tiff image from.
[in] scale Scale factor to apply to image pixels (8 bit values read from tiff file are mapped to (val-offset)*scale.
[in] offset Offset to apply to image pixels (8 bit values read from tiff file are mapped to (val-offset)*scale.
Definition at line 28 of file sopt_image.c.
References SOPT_ERROR_MEM_ALLOC_CHECK().
Referenced by main().
int spot_image_tiff_write (double * img, int nx, int ny, char * filename, double scale, double offset)
Write RGBA tiff image to file from greyscale image (the greyscale image is written to the red, green and blue channels of the RGBA image).
Parameters
[in] img Greyscale image written to tiff file.
[in] nx Dimension of image in x direction.
[in] ny Dimension of image in y direction.
[in] filename Name of file to write tiff image to.
[in] scale Scale factor to apply to image pixels (8 bit values written to tiff file are transformed by (img-offset)*scale.
[in] offset Offset to apply to image pixels (8 bit values written to tiff file are transformed by (img-offset)*scale.
Definition at line 88 of file sopt_image.c.
References SOPT_ERROR_MEM_ALLOC_CHECK().
Referenced by main().