src/c/sopt_test.c File Reference
sopt_test.c File Reference
#include "sopt_config.h"
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <fftw3.h>
#include <math.h>
#include "sopt_utility.h"
#include "sopt_error.h"
#include "sopt_prox.h"
#include "sopt_ran.h"
#include "sopt_meas.h"
#include "sopt_tv.h"
#include "sopt_l1.h"
#include "sopt_wavelet.h"
#include "sopt_sara.h"
#include "sopt_sparsemat.h"
#include "sopt_image.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 30 of file sopt_test.c.
References sopt_sara_param::ndict, sopt_sara_param::real, SOPT_ERROR_GENERIC(), SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_ran_gasdev2(), sopt_ran_knuthshuffle(), sopt_sara_analysisop(), sopt_sara_free(), sopt_sara_initop(), sopt_sara_synthesisop(), SOPT_WAVELET_DB1, SOPT_WAVELET_DB2, SOPT_WAVELET_DB3, SOPT_WAVELET_DB4, SOPT_WAVELET_DB5, SOPT_WAVELET_DB6, SOPT_WAVELET_DB7, SOPT_WAVELET_DB8, spot_image_tiff_read(), and spot_image_tiff_write().