include/sopt_wavelet.h File Reference
sopt_wavelet.h File Reference
Data Structures
struct sopt_wavelet_param
Enumerations
enum sopt_wavelet_type {
SOPT_WAVELET_Dirac, SOPT_WAVELET_DB1, SOPT_WAVELET_DB2, SOPT_WAVELET_DB3,
SOPT_WAVELET_DB4, SOPT_WAVELET_DB5, SOPT_WAVELET_DB6, SOPT_WAVELET_DB7,
SOPT_WAVELET_DB8, SOPT_WAVELET_DB9, SOPT_WAVELET_DB10
}
Functions
void sopt_wavelet_convd (double *out_l, double *out_h, double *in, double *h0, double *h1, int length_sig, int length_filt)
void sopt_wavelet_convu (double *out, double *in_l, double *in_h, double *h0, double *h1, int length_sig, int length_filt)
void sopt_wavelet_gdfwtr (double *w, double *x, sopt_wavelet_param param_wav)
void sopt_wavelet_gdiwtr (double *x, double *w, sopt_wavelet_param param_wav)
void sopt_wavelet_gdfwtc (complex double *w, complex double *x, sopt_wavelet_param param_wav)
void sopt_wavelet_gdiwtc (complex double *x, complex double *w, sopt_wavelet_param param_wav)
void sopt_wavelet_initwav (sopt_wavelet_param *param)
Enumeration Type Documentation
enum sopt_wavelet_type
Options for the basis to be included in the SARA operator. As for now we support the Dirac basis and the first 10 Daubechies orthornormal wavelet basis.
Enumerator:
SOPT_WAVELET_Dirac
SOPT_WAVELET_DB1
SOPT_WAVELET_DB2
SOPT_WAVELET_DB3
SOPT_WAVELET_DB4
SOPT_WAVELET_DB5
SOPT_WAVELET_DB6
SOPT_WAVELET_DB7
SOPT_WAVELET_DB8
SOPT_WAVELET_DB9
SOPT_WAVELET_DB10
Definition at line 18 of file sopt_wavelet.h.
Function Documentation
void sopt_wavelet_convd (double * out_l, double * out_h, double * in, double * h0, double * h1, int length_sig, int length_filt)
Convolve the signal "in" with "h0" and "h1".
Parameters:
[out] out_l Low-pass filtered signal.
[out] out_h High-pass filtered signal.
[in] in Input data.
[in] h0 Aproximation filter coefficients.
[in] h1 Detail filter coefficients.
[in] length_sig Input signal length.
[in] length_filt Filter coefficients length.
Definition at line 36 of file sopt_wavelet.c.
Referenced by sopt_wavelet_gdfwtr().
void sopt_wavelet_convu (double * out, double * in_l, double * in_h, double * h0, double * h1, int length_sig, int length_filt)
Convolve signals "in_l" and "in_h" with "h0" and "h1" respectively, and add them in out.
Parameters:
[out] out Output signal.
[in] in_l Low-pass input signal.
[in] in_h High-pass input signal.
[in] h0 Aproximation filter coefficients.
[in] h1 Detail filter coefficients.
[in] length_sig Input signal length.
[in] length_filt Filter coefficients length.
Definition at line 72 of file sopt_wavelet.c.
Referenced by sopt_wavelet_gdiwtr().
void sopt_wavelet_gdfwtc (complex double * w, complex double * x, sopt_wavelet_param param_wav)
Compute wavelets coefficients of a complex 2D signal x stored in column major order.
Parameters:
[out] w Output wavelet complex coefficients.
[in] x Input 2D complex signal.
[in] param_wav Structure with the necessary parameters for the wavelet decomposition.
Definition at line 320 of file sopt_wavelet.c.
References sopt_wavelet_param::nx1, sopt_wavelet_param::nx2, SOPT_ERROR_MEM_ALLOC_CHECK(), SOPT_WAVELET_Dirac, sopt_wavelet_gdfwtr(), and sopt_wavelet_param::type.
Referenced by sopt_sara_analysisop().
void sopt_wavelet_gdfwtr (double * w, double * x, sopt_wavelet_param param_wav)
Compute wavelets coefficients of a real 2D signal x stored in column major order.
Parameters:
[out] w Output wavelet coefficients.
[in] x Input 2D signal.
[in] param_wav Structure with the necessary parameters for the wavelet decomposition.
Definition at line 107 of file sopt_wavelet.c.
References sopt_wavelet_param::h, sopt_wavelet_param::h_size, max, sopt_wavelet_param::nb_levels, sopt_wavelet_param::nx1, sopt_wavelet_param::nx2, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_wavelet_convd(), SOPT_WAVELET_Dirac, and sopt_wavelet_param::type.
Referenced by sopt_sara_analysisop(), and sopt_wavelet_gdfwtc().
void sopt_wavelet_gdiwtc (complex double * x, complex double * w, sopt_wavelet_param param_wav)
Inverse wavelet transform (on complex 2D signal).
Parameters:
[out] x Output 2D complex signal.
[in] w Input complex wavelet coefficients.
[in] param_wav Structure with the necessary parameters for the wavelet decomposition.
Definition at line 373 of file sopt_wavelet.c.
References sopt_wavelet_param::nx1, sopt_wavelet_param::nx2, SOPT_ERROR_MEM_ALLOC_CHECK(), SOPT_WAVELET_Dirac, sopt_wavelet_gdiwtr(), and sopt_wavelet_param::type.
Referenced by sopt_sara_synthesisop().
void sopt_wavelet_gdiwtr (double * x, double * w, sopt_wavelet_param param_wav)
Inverse wavelet transform (on real 2D signal).
Parameters:
[out] x Output 2D signal.
[in] w Input wavelet coefficients.
[in] param_wav Structure with the necessary parameters for the wavelet decomposition.
Definition at line 208 of file sopt_wavelet.c.
References sopt_wavelet_param::h, sopt_wavelet_param::h_size, max, sopt_wavelet_param::nb_levels, sopt_wavelet_param::nx1, sopt_wavelet_param::nx2, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_wavelet_convu(), SOPT_WAVELET_Dirac, and sopt_wavelet_param::type.
Referenced by sopt_sara_synthesisop(), and sopt_wavelet_gdiwtc().
void sopt_wavelet_initwav (sopt_wavelet_param * param)
This function initializes the filter coefficients for the wavelet transform.
Parameters:
[out] param Structure with the necessary parameters for the wavelet decomposition.
Definition at line 426 of file sopt_wavelet.c.
References sopt_wavelet_param::h, sopt_wavelet_param::h_size, SOPT_ERROR_MEM_ALLOC_CHECK(), SOPT_WAVELET_DB1, SOPT_WAVELET_DB10, SOPT_WAVELET_DB2, SOPT_WAVELET_DB3, SOPT_WAVELET_DB4, SOPT_WAVELET_DB5, SOPT_WAVELET_DB6, SOPT_WAVELET_DB7, SOPT_WAVELET_DB8, SOPT_WAVELET_DB9, SOPT_WAVELET_Dirac, and sopt_wavelet_param::type.
Referenced by sopt_sara_initop().