include/sopt_prox.h File Reference
sopt_prox.h File Reference
#include "sopt_config.h"
#include <complex.h>
Data Structures
struct sopt_prox_l1param
struct sopt_prox_tvparam
struct sopt_prox_l2bparam
struct sopt_prox_wl2param
Functions
void sopt_prox_l1 (void *xout, void *xin, int nx, int nr, void(*Psi)(void *out, void *in, void **data), void **Psi_data, void(*Psit)(void *out, void *in, void **data), void **Psit_data, double *weights, double lambda, int real_data, sopt_prox_l1param param, void *dummy, void *sol, void *u, void *v)
void sopt_prox_tv (void *xout, void *xin, int nx1, int nx2, double lambda, int real_data, sopt_prox_tvparam param, void *r, void *s, void *pold, void *qold, void *dx, void *dy)
void sopt_prox_wtv (void *xout, void *xin, int nx1, int nx2, double lambda, int real_data, sopt_prox_tvparam param, double *wt_dx, double *wt_dy, void *r, void *s, void *xaux, void *pold, void *qold, void *dx, void *dy)
void sopt_prox_l2b (void *xout, void *xin, int nx, void *y, int ny, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, double epsilon, int real_data, sopt_prox_l2bparam param, void *dummy, void *u, void *v)
void sopt_prox_wl2 (void *xout, void *xin, int nx, int nr, void(*Psi)(void *out, void *in, void **data), void **Psi_data, void(*Psit)(void *out, void *in, void **data), void **Psit_data, double *weights, double lambda, int real_data, sopt_prox_wl2param param, void *dummy, void *sol, void *u)
Function Documentation
void sopt_prox_l1 (void * xout, void * xin, int nx, int nr, void(*)(void *out, void *in, void **data) Psi, void ** Psi_data, void(*)(void *out, void *in, void **data) Psit, void ** Psit_data, double * weights, double lambda, int real_data, sopt_prox_l1param param, void * dummy, void * sol, void * u, void * v)
This function computes the prox operator of the l1 norm for the input vector . It solves the problem:
where is the sparsifying operator. The solution is denoted .
Parameters
[out] xout Output solution ().
[in] xin Input vector ().
[in] nx Dimension of the signal ().
[in] nr Dimension of the signal in the representation domain ().
[in] Psi Pointer to the synthesis sparsity operator .
[in] Psi_data Data structure associated to .
[in] Psit Pointer to the analysis sparsity operator .
[in] Psit_data Data structure associated to .
[in] weights weights vector.
[in] lambda Convergence parameter .
[in] real_data Flag for real or complex data. 1 if real 0 complex.
[in] param Data structure with the parameters of the optimization.
[in] dummy Auxiliary vector. Dimension: nr.
[in] sol Auxiliary vector. Dimension: nx.
[in] u Auxiliary vector. Dimension: nr.
[in] v Auxiliary vector. Dimension: nr.
Definition at line 52 of file sopt_prox.c.
References sopt_prox_l1param::max_iter, sopt_prox_l1param::nu, sopt_prox_l1param::pos, sopt_prox_l1param::rel_obj, sopt_utility_l1normc(), sopt_utility_l1normr(), sopt_utility_projposc(), sopt_utility_projposr(), sopt_utility_softthc(), sopt_utility_softthr(), sopt_prox_l1param::tight, and sopt_prox_l1param::verbose.
Referenced by sopt_l1_solver(), and sopt_l1_solver_aadmm().
void sopt_prox_l2b (void * xout, void * xin, int nx, void * y, int ny, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, double epsilon, int real_data, sopt_prox_l2bparam param, void * dummy, void * u, void * v)
This function computes the projection onto the epsilon l2 ball for the input vector . It solves the problem:
where is the measurement operator, is the ball radius and is the measurement vector. The solution is denoted .
Parameters
[out] xout Output solution ().
[in] xin Input vector ().
[in] nx Dimension of the signal ().
[in] y Measurement vector ().
[in] ny Dimension of measurement vector, i.e. number of measurements ().
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to .
[in] At Pointer to the the adjoint of the measurement operator .
[in] At_data Data structure associated to .
[in] epsilon Radius of the l2 ball .
[in] real_data Flag for real or complex data. 1 if real 0 complex.
[in] param Data structure with the parameters of the optimization.
[in] dummy Auxiliary vector. Dimension: ny.
[in] u Auxiliary vector. Dimension: ny.
[in] v Auxiliary vector. Dimension: ny.
Definition at line 722 of file sopt_prox.c.
References sopt_prox_l2bparam::bcktrk, sopt_prox_l2bparam::max_iter, min, sopt_prox_l2bparam::nu, sopt_prox_l2bparam::pos, sopt_prox_l2bparam::real, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_utility_btrackc(), sopt_utility_btrackr(), sopt_utility_projposc(), sopt_utility_projposr(), sopt_utility_projreal(), sopt_prox_l2bparam::tight, sopt_prox_l2bparam::tol, and sopt_prox_l2bparam::verbose.
Referenced by sopt_l1_solver(), sopt_l2_solver(), and sopt_tv_solver().
void sopt_prox_tv (void * xout, void * xin, int nx1, int nx2, double lambda, int real_data, sopt_prox_tvparam param, void * r, void * s, void * pold, void * qold, void * dx, void * dy)
This function computes the prox operator of the TV norm for the input image . It solves the problem:
*The solution is denoted .
Parameters
[out] xout Output solution ().
[in] xin Input image ().
[in] nx1 Number of columns of the input image
[in] nx2 Number of rows of the input image
[in] lambda Convergence parameter .
[in] real_data Flag for real or complex data. 1 if real 0 complex.
[in] param Data structure with the parameters of the optimization.
[in] r Auxiliary vector. Dimension: nx=nx1*nx2.
[in] s Auxiliary vector. Dimension: nx.
[in] pold Auxiliary vector. Dimension: nx.
[in] qold Auxiliary vector. Dimension: nx.
[in] dx Auxiliary vector. Dimension: nx.
[in] dy Auxiliary vector. Dimension: nx.
Definition at line 288 of file sopt_prox.c.
References max, sopt_prox_tvparam::max_iter, sopt_prox_tvparam::rel_obj, sopt_utility_divergencec(), sopt_utility_divergencer(), sopt_utility_gradientc(), sopt_utility_gradientr(), sopt_utility_tvnormc(), sopt_utility_tvnormr(), and sopt_prox_tvparam::verbose.
Referenced by sopt_tv_solver().
void sopt_prox_wl2 (void * xout, void * xin, int nx, int nr, void(*)(void *out, void *in, void **data) Psi, void ** Psi_data, void(*)(void *out, void *in, void **data) Psit, void ** Psit_data, double * weights, double lambda, int real_data, sopt_prox_wl2param param, void * dummy, void * sol, void * u)
This function computes the prox operator of the weighted l2 norm for the input vector . It solves the problem:
where is the sparsifying operator. The solution is denoted .
Parameters
[out] xout Output solution ().
[in] xin Input vector ().
[in] nx Dimension of the signal ().
[in] nr Dimension of the signal in the representation domain ().
[in] Psi Pointer to the synthesis sparsity operator .
[in] Psi_data Data structure associated to .
[in] Psit Pointer to the analysis sparsity operator .
[in] Psit_data Data structure associated to .
[in] weights weights vector.
[in] lambda Convergence parameter .
[in] real_data Flag for real or complex data. 1 if real 0 complex.
[in] param Data structure with the parameters of the optimization.
[in] dummy Auxiliary vector. Dimension: nr.
[in] sol Auxiliary vector. Dimension: nx.
[in] u Auxiliary vector. Dimension: nr.
Definition at line 1066 of file sopt_prox.c.
References sopt_prox_wl2param::max_iter, sopt_prox_wl2param::nu, sopt_prox_wl2param::pos, sopt_prox_wl2param::rel_obj, sopt_utility_l1normc(), sopt_utility_l1normr(), sopt_utility_projposc(), sopt_utility_projposr(), sopt_utility_sql2normc(), sopt_utility_sql2normr(), sopt_prox_wl2param::tight, and sopt_prox_wl2param::verbose.
Referenced by sopt_l2_solver().
void sopt_prox_wtv (void * xout, void * xin, int nx1, int nx2, double lambda, int real_data, sopt_prox_tvparam param, double * wt_dx, double * wt_dy, void * r, void * s, void * xaux, void * pold, void * qold, void * dx, void * dy)
This function computes the prox operator of the weighted TV norm for the input image . It solves the problem:
*The solution is denoted .
Parameters
[out] xout Output solution ().
[in] xin Input image ().
[in] nx1 Number of columns of the input image
[in] nx2 Number of rows of the input image
[in] lambda Convergence parameter .
[in] real_data Flag for real or complex data. 1 if real 0 complex.
[in] param Data structure with the parameters of the optimization.
[in] wt_dx Weight vector in x direction. Dimension: nx.
[in] wt_dy Weight vector in y direction. Dimension: nx.
[in] r Auxiliary vector. Dimension: nx.
[in] s Auxiliary vector. Dimension: nx.
[in] xaux Auxiliary vector. Dimension: nx.
[in] pold Auxiliary vector. Dimension: nx.
[in] qold Auxiliary vector. Dimension: nx.
[in] dx Auxiliary vector. Dimension: nx.
[in] dy Auxiliary vector. Dimension: nx.
Definition at line 493 of file sopt_prox.c.
References max, sopt_prox_tvparam::max_iter, sopt_prox_tvparam::rel_obj, sopt_utility_divergencec(), sopt_utility_divergencer(), sopt_utility_gradientc(), sopt_utility_gradientr(), sopt_utility_wtvnormc(), sopt_utility_wtvnormr(), and sopt_prox_tvparam::verbose.
Referenced by sopt_tv_sdmm().