src/c/sopt_utility.c File Reference
sopt_utility.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <string.h>
#include <math.h>
#include <cblas.h>
#include "sopt_error.h"
#include "sopt_utility.h"
Defines
#define min(a, b) (a<b?a:b)
#define max(a, b) (a<b?b:a)
Functions
complex double sopt_utility_softthc (complex double x, double T)
double sopt_utility_softthr (double x, double T)
double sopt_utility_l1normc (complex double *x, double *w, int dim)
double sopt_utility_l1normr (double *x, double *w, int dim)
double sopt_utility_sql2normc (complex double *x, double *w, int dim)
double sopt_utility_sql2normr (double *x, double *w, int dim)
double sopt_utility_tvnormc (complex double *x, int dim1, int dim2)
double sopt_utility_tvnormr (double *x, int dim1, int dim2)
double sopt_utility_wtvnormc (complex double *x, double *wt_dx, double *wt_dy, int dim1, int dim2)
double sopt_utility_wtvnormr (double *x, double *wt_dx, double *wt_dy, int dim1, int dim2)
void sopt_utility_gradientc (complex double *dx, complex double *dy, complex double *xin, int dim1, int dim2)
void sopt_utility_gradientr (double *dx, double *dy, double *xin, int dim1, int dim2)
void sopt_utility_divergencec (complex double *xout, complex double *dx, complex double *dy, int dim1, int dim2)
void sopt_utility_divergencer (double *xout, double *dx, double *dy, int dim1, int dim2)
void sopt_utility_projposc (complex double *xout, complex double *xin, int dim)
void sopt_utility_projposr (double *xout, double *xin, int dim)
void sopt_utility_projreal (complex double *xout, complex double *xin, int dim)
complex double sopt_utility_dotpc (complex double *xin, complex double *yin, int dim)
double sopt_utility_dotpr (double *xin, double *yin, int dim)
double sopt_utility_btrackc (complex double *v, complex double *r, complex double *w, complex double *dummy, complex double *xaux, complex double *xout, complex double *xin, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, int nx, int ny, double nu, double epsilon)
double sopt_utility_btrackr (double *v, double *r, double *w, double *dummy, double *xaux, double *xout, double *xin, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, int nx, int ny, double nu, double epsilon)
void sopt_utility_cgsolc (complex double *xout, complex double *xin, complex double *v, complex double *r, complex double *p, complex double *ap, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, int nx, int ny, double tol, int nit, int verbose)
void sopt_utility_cgsolr (double *xout, double *xin, double *v, double *r, double *p, double *ap, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, int nx, int ny, double tol, int nit, int verbose)
Define Documentation
#define max (a, b) (a<b?b:a)
Definition at line 26 of file sopt_utility.c.
Referenced by sopt_utility_softthc(), and sopt_utility_softthr().
#define min (a, b) (a<b?a:b)
Definition at line 25 of file sopt_utility.c.
Referenced by sopt_utility_btrackc(), and sopt_utility_btrackr().
Function Documentation
double sopt_utility_btrackc (complex double * v, complex double * r, complex double * w, complex double * dummy, complex double * xaux, complex double * xout, complex double * xin, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, int nx, int ny, double nu, double epsilon)
Performs a bactracking search for the appropriate Lipchitz constant in sopt_prox_l2b. Complex case.
Parameters:
[out] v update vector in the measurement domain. Complex vector of dimension ny.
[in] r Previuos residual. Complex vector of dimension ny.
[in] w Previous update point. Complex vector of dimension ny.
[in] dummy Auxiliary complex vector of dimension ny.
[in] xaux Auxiliary complex vector of dimension nx.
[in] xout Previous solution. Complex vector of dimension nx.
[in] xin Input point. Complex vector of dimension nx.
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to .
[in] At Pointer to the the adjoint of the measurement operator .
[in] At_data Data structure associated to .
[in] nx Dimension of the solution space.
[in] ny Dimension of the measurement space.
[in] nu Initial operator norm.
[in] epsilon Radius of the l2 ball .
Definition at line 562 of file sopt_utility.c.
References min, and sopt_utility_dotpc().
Referenced by sopt_prox_l2b().
double sopt_utility_btrackr (double * v, double * r, double * w, double * dummy, double * xaux, double * xout, double * xin, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, int nx, int ny, double nu, double epsilon)
Performs a bactracking search for the appropriate Lipchitz constant in sopt_prox_l2b. Real case.
Parameters:
[out] v update vector in the measurement domain. Real vector of dimension ny.
[in] r Previuos residual. Real vector of dimension ny.
[in] w Previous update point. Real vector of dimension ny.
[in] dummy Auxiliary real vector of dimension ny.
[in] xaux Auxiliary real vector of dimension nx.
[in] xout Previous solution. Real vector of dimension nx.
[in] xin Input point. Real vector of dimension nx.
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to .
[in] At Pointer to the the adjoint of the measurement operator .
[in] At_data Data structure associated to .
[in] nx Dimension of the solution space.
[in] ny Dimension of the measurement space.
[in] nu Initial operator norm.
[in] epsilon Radius of the l2 ball .
Definition at line 695 of file sopt_utility.c.
References min, and sopt_utility_dotpr().
Referenced by sopt_prox_l2b().
void sopt_utility_cgsolc (complex double * xout, complex double * xin, complex double * v, complex double * r, complex double * p, complex double * ap, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, int nx, int ny, double tol, int nit, int verbose)
Conjugate gradient routine to solve the linear system
in the SDMM algorithm. Complex case.
Parameters:
[out] xout Solution of the system. Complex vector of dimension nx.
[in] xin . Complex vector of dimension nx.
[in] v Auxiliary complex vector of dimension ny.
[in] r Auxiliary complex vector of dimension nx.
[in] p Auxiliary complex vector of dimension nx.
[in] ap Auxiliary complex vector of dimension nx.
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to .
[in] At Pointer to the the adjoint of the measurement operator .
[in] At_data Data structure associated to .
[in] nx Dimension of the solution space.
[in] ny Dimension of the measurement space.
[in] tol tolerance on the relative residual .
[in] nit Maximum number of iterations.
[in] verbose verbosity.
Definition at line 818 of file sopt_utility.c.
References sopt_utility_dotpc().
Referenced by sopt_l1_sdmm(), and sopt_tv_sdmm().
void sopt_utility_cgsolr (double * xout, double * xin, double * v, double * r, double * p, double * ap, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, int nx, int ny, double tol, int nit, int verbose)
Conjugate gradient routine to solve the linear system
in the SDMM algorithm. Real case.
Parameters:
[out] xout Solution of the system. Real vector of dimension nx.
[in] xin . Real vector of dimension ny.
[in] v Auxiliary real vector of dimension ny.
[in] r Auxiliary real vector of dimension nx.
[in] p Auxiliary real vector of dimension nx.
[in] ap Auxiliary real vector of dimension nx.
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to .
[in] At Pointer to the the adjoint of the measurement operator .
[in] At_data Data structure associated to .
[in] nx Dimension of the solution space.
[in] ny Dimension of the measurement space.
[in] tol tolerance on the relative residual .
[in] nit Maximum number of iterations.
[in] verbose verbosity.
Definition at line 940 of file sopt_utility.c.
References sopt_utility_dotpr().
Referenced by sopt_l1_sdmm(), and sopt_tv_sdmm().
void sopt_utility_divergencec (complex double * xout, complex double * dx, complex double * dy, int dim1, int dim2)
Compute the divergence of a complex discrete image (adjoint of the gradient).
Parameters:
[out] xout Output image.
[in] dx Vertical image gradient.
[in] dy Horizontal image gradient.
[in] dim1 Number of elements in the first dimension.
[in] dim2 Number of elements in the second dimension.
Definition at line 393 of file sopt_utility.c.
Referenced by sopt_prox_tv(), and sopt_prox_wtv().
void sopt_utility_divergencer (double * xout, double * dx, double * dy, int dim1, int dim2)
Compute the divergence of a real discrete image (adjoint of the gradient).
Parameters:
[out] xout Output image.
[in] dx Vertical image gradient.
[in] dy Horizontal image gradient.
[in] dim1 Number of elements in the first dimension.
[in] dim2 Number of elements in the second dimension.
Definition at line 423 of file sopt_utility.c.
Referenced by sopt_prox_tv(), and sopt_prox_wtv().
complex double sopt_utility_dotpc (complex double * xin, complex double * yin, int dim)
Compute the dot product of two complex vectors.
Return values:
p Dot product output, complex number.
Parameters:
[in] xin Input complex vector.
[in] yin Input complex vector.
[in] dim Dimension of the input vectors.
Definition at line 509 of file sopt_utility.c.
Referenced by sopt_utility_btrackc(), and sopt_utility_cgsolc().
double sopt_utility_dotpr (double * xin, double * yin, int dim)
Compute the dot product of two real vectors.
Return values:
p Dot product output, real number.
Parameters:
[in] xin Input real vector.
[in] yin Input real vector.
[in] dim Dimension of the input vectors.
Definition at line 529 of file sopt_utility.c.
Referenced by sopt_utility_btrackr(), and sopt_utility_cgsolr().
void sopt_utility_gradientc (complex double * dx, complex double * dy, complex double * xin, int dim1, int dim2)
Compute the gradient of a complex discrete image.
Parameters:
[out] dx Vertical image gradient.
[out] dy Horizontal image gradient.
[in] xin Input image.
[in] dim1 Number of elements in the first dimension.
[in] dim2 Number of elements in the second dimension.
Definition at line 314 of file sopt_utility.c.
Referenced by sopt_prox_tv(), sopt_prox_wtv(), sopt_tv_rwsdmm(), sopt_utility_tvnormc(), and sopt_utility_wtvnormc().
void sopt_utility_gradientr (double * dx, double * dy, double * xin, int dim1, int dim2)
Compute the gradient of a real discrete image.
Parameters:
[out] dx Vertical image gradient.
[out] dy Horizontal image gradient.
[in] xin Input image.
[in] dim1 Number of elements in the first dimension.
[in] dim2 Number of elements in the second dimension.
Definition at line 354 of file sopt_utility.c.
Referenced by sopt_prox_tv(), sopt_prox_wtv(), sopt_tv_rwsdmm(), sopt_utility_tvnormr(), and sopt_utility_wtvnormr().
double sopt_utility_l1normc (complex double * x, double * w, int dim)
Compute the weighted l1 norm of a complex vector.
Parameters:
[in] x Input vector.
[in] w Weights vector.
[in] dim Dimension of the input vector.
Return values:
norm Value of the l1 norm.
Definition at line 76 of file sopt_utility.c.
Referenced by sopt_l1_sdmm(), sopt_l1_solver(), sopt_prox_l1(), and sopt_prox_wl2().
double sopt_utility_l1normr (double * x, double * w, int dim)
Compute the weighted l1 norm of a real vector.
Parameters:
[in] x Input vector.
[in] w Weights vector.
[in] dim Dimension of the input vector.
Return values:
norm Value of the l1 norm.
Definition at line 97 of file sopt_utility.c.
Referenced by sopt_l1_sdmm(), sopt_l1_solver(), sopt_prox_l1(), and sopt_prox_wl2().
void sopt_utility_projposc (complex double * xout, complex double * xin, int dim)
Compute the projection onto the positive orthant of a complex vector x.
Parameters:
[out] xout Output positive vector.
[in] xin Input complex vector
[in] dim Dimension of the input vector
Definition at line 452 of file sopt_utility.c.
Referenced by sopt_l1_rwsdmm(), sopt_l1_sdmm(), sopt_prox_l1(), sopt_prox_l2b(), sopt_prox_wl2(), sopt_tv_rwsdmm(), and sopt_tv_sdmm().
void sopt_utility_projposr (double * xout, double * xin, int dim)
Compute the projection onto the positive orthant of a real vector x.
Parameters:
[out] xout Output positive vector.
[in] xin Input complex vector
[in] dim Dimension of the input vector
Definition at line 473 of file sopt_utility.c.
Referenced by sopt_l1_rwsdmm(), sopt_l1_sdmm(), sopt_prox_l1(), sopt_prox_l2b(), sopt_prox_wl2(), sopt_tv_rwsdmm(), and sopt_tv_sdmm().
void sopt_utility_projreal (complex double * xout, complex double * xin, int dim)
Compute the projection onto the real orthant of a complex vector x.
Parameters:
[out] xout Output real vector.
[in] xin Input complex vector
[in] dim Dimension of the input vector
Definition at line 492 of file sopt_utility.c.
Referenced by sopt_prox_l2b().
complex double sopt_utility_softthc (complex double x, double T)
Scalar soft thresolding operator. Complex case.
Parameters:
[in] x Input value.
[in] T Thresold.
Return values:
xout Thresolded value.
Definition at line 33 of file sopt_utility.c.
References max.
Referenced by sopt_l1_sdmm(), and sopt_prox_l1().
double sopt_utility_softthr (double x, double T)
Scalar soft thresolding operator. Real case.
Parameters:
[in] x Input value.
[in] T Thresold.
Return values:
xout Thresolded value.
Definition at line 54 of file sopt_utility.c.
References max.
Referenced by sopt_l1_sdmm(), and sopt_prox_l1().
double sopt_utility_sql2normc (complex double * x, double * w, int dim)
Compute the weighted squared l2 norm of a complex vector.
Parameters:
[in] x Input vector.
[in] w Weights vector.
[in] dim Dimention of the input vector.
Return values:
norm Value of the l2 norm.
Definition at line 118 of file sopt_utility.c.
Referenced by sopt_l2_solver(), and sopt_prox_wl2().
double sopt_utility_sql2normr (double * x, double * w, int dim)
Compute the weighted squared l2 norm of a real vector.
Parameters:
[in] x Input vector.
[in] w Weights vector.
[in] dim Dimention of the input vector.
Return values:
norm Value of the l2 norm.
Definition at line 139 of file sopt_utility.c.
Referenced by sopt_l2_solver(), and sopt_prox_wl2().
double sopt_utility_tvnormc (complex double * x, int dim1, int dim2)
Compute the tv norm of a complex discrete image.
Parameters:
[in] x Input image.
[in] dim1 Number of elements in the first dimension.
[in] dim2 Number of elements in the second dimension.
Return values:
norm Value of the tv norm.
Definition at line 160 of file sopt_utility.c.
References SOPT_ERROR_MEM_ALLOC_CHECK(), and sopt_utility_gradientc().
Referenced by sopt_prox_tv(), and sopt_tv_solver().
double sopt_utility_tvnormr (double * x, int dim1, int dim2)
Compute the tv norm of a real discrete image.
Parameters:
[in] x Input image.
[in] dim1 Number of elements in the first dimension.
[in] dim2 Number of elements in the second dimension.
Return values:
norm Value of the tv norm.
Definition at line 195 of file sopt_utility.c.
References SOPT_ERROR_MEM_ALLOC_CHECK(), and sopt_utility_gradientr().
Referenced by sopt_prox_tv(), and sopt_tv_solver().
double sopt_utility_wtvnormc (complex double * x, double * wt_dx, double * wt_dy, int dim1, int dim2)
Compute the weighted tv norm of a complex discrete image.
Parameters:
[in] x Input image.
[in] wt_dx Weights in the x direction.
[in] wt_dy Weights in the y direction.
[in] dim1 Number of elements in the first dimension.
[in] dim2 Number of elements in the second dimension.
Return values:
norm Value of the tv norm.
Definition at line 231 of file sopt_utility.c.
References SOPT_ERROR_MEM_ALLOC_CHECK(), and sopt_utility_gradientc().
Referenced by sopt_prox_wtv(), and sopt_tv_sdmm().
double sopt_utility_wtvnormr (double * x, double * wt_dx, double * wt_dy, int dim1, int dim2)
Compute the weighted tv norm of a real discrete image.
Parameters:
[in] x Input image.
[in] wt_dx Weights in the x direction.
[in] wt_dy Weights in the y direction.
[in] dim1 Number of elements in the first dimension.
[in] dim2 Number of elements in the second dimension.
Return values:
norm Value of the tv norm.
Definition at line 273 of file sopt_utility.c.
References SOPT_ERROR_MEM_ALLOC_CHECK(), and sopt_utility_gradientr().
Referenced by sopt_prox_wtv(), and sopt_tv_sdmm().