include/sopt_sara.h File Reference
sopt_sara.h File Reference
#include "sopt_config.h"
Data Structures
struct sopt_sara_param
Functions
void sopt_sara_initop (sopt_sara_param *param, int nx1, int nx2, int nb_levels, sopt_wavelet_type *dict_types)
void sopt_sara_free (sopt_sara_param *param)
void sopt_sara_analysisop (void *out, void *in, void **data)
void sopt_sara_synthesisop (void *out, void *in, void **data)
Function Documentation
void sopt_sara_analysisop (void * out, void * in, void ** data)
This function computes the analysis operator for concatenation of bases.
Parameters
[out] out Output data.
[in] in Input data.
[in] data array containing the necessary parameters for the operator. data[0] Parameter structure for the operator of type sopt_sara_param.
Definition at line 82 of file sopt_sara.c.
References sopt_sara_param::ndict, sopt_wavelet_param::nx1, sopt_wavelet_param::nx2, sopt_sara_param::real, sopt_wavelet_gdfwtc(), sopt_wavelet_gdfwtr(), and sopt_sara_param::wav_params.
Referenced by main().
void sopt_sara_free (sopt_sara_param * param)
This function frees all memory used to store the SARA operator parameters.
Parameters
[in] param Structure with the necessary parameters for the operator.
Definition at line 57 of file sopt_sara.c.
References sopt_wavelet_param::h, sopt_sara_param::ndict, and sopt_sara_param::wav_params.
Referenced by main().
void sopt_sara_initop (sopt_sara_param * param, int nx1, int nx2, int nb_levels, sopt_wavelet_type * dict_types)
This function initializes the parameters for the SARA dictionary.
Parameters
[out] param Structure with the necessary parameters for the operator.
[in] nx1 Number of rows in the input image.
[in] nx2 Number of rows in the input image.
[in] nb_levels Number of levels in the wavelet decomposition.
[in] dict_types array containing the list of basis used in the operator.
Definition at line 30 of file sopt_sara.c.
References sopt_wavelet_param::nb_levels, sopt_sara_param::ndict, sopt_wavelet_param::nx1, sopt_wavelet_param::nx2, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_wavelet_initwav(), sopt_wavelet_param::type, and sopt_sara_param::wav_params.
Referenced by main().
void sopt_sara_synthesisop (void * out, void * in, void ** data)
This function computes the synthesis operator for concatenation of bases.
Warning
Input data is overwritten on output.
Parameters
[out] out Output data, dimension nx.
[in,out] in Input data, dimension q*nx. Overwritten on output.
[in] data array containing the necessary parameters for the operator. data[0] Parameter structure for the operator
Definition at line 154 of file sopt_sara.c.
References sopt_sara_param::ndict, sopt_wavelet_param::nx1, sopt_wavelet_param::nx2, sopt_sara_param::real, sopt_wavelet_gdiwtc(), sopt_wavelet_gdiwtr(), and sopt_sara_param::wav_params.
Referenced by main().