include/sopt_error.h File Reference
sopt_error.h File Reference
#include "sopt_config.h"
#include <stdio.h>
#include <stdlib.h>
Functions
void SOPT_ERROR_GENERIC (char *comment)
void SOPT_ERROR_MEM_ALLOC_CHECK (void *pointer)
Detailed Description
Error functions used in SOPT package.
Definition in file sopt_error.h.
Function Documentation
void SOPT_ERROR_GENERIC (char * comment) inline
Display error message and halt program execution.
Parameters
[in] comment Additional comment to display.
Authors
Jason McEwen
Definition at line 12 of file sopt_error.h.
Referenced by main(), SOPT_ERROR_MEM_ALLOC_CHECK(), and sopt_ran_knuthshuffle().
void SOPT_ERROR_MEM_ALLOC_CHECK (void * pointer) inline
Test whether memory allocation was successful (i.e. check allocated pointer not NULL) and throw a generic error if allocation failed.
Parameters
[in] pointer Pointer that should point to allocated memory is memory allocation was successful.
Authors
Jason McEwen
Definition at line 22 of file sopt_error.h.
References SOPT_ERROR_GENERIC().
Referenced by main(), sopt_l1_rwmin(), sopt_l1_rwsdmm(), sopt_l1_sdmm(), sopt_l1_solver(), sopt_l1_solver_aadmm(), sopt_l2_solver(), sopt_prox_l2b(), sopt_ran_knuthshuffle(), sopt_sara_initop(), sopt_sparsemat_explictmat(), sopt_tv_rwsdmm(), sopt_tv_sdmm(), sopt_tv_solver(), sopt_utility_tvnormc(), sopt_utility_tvnormr(), sopt_utility_wtvnormc(), sopt_utility_wtvnormr(), sopt_wavelet_gdfwtc(), sopt_wavelet_gdfwtr(), sopt_wavelet_gdiwtc(), sopt_wavelet_gdiwtr(), sopt_wavelet_initwav(), spot_image_tiff_read(), and spot_image_tiff_write().