src/c/sopt_ran.c File Reference
sopt_ran.c File Reference
#include "sopt_config.h"
#include <math.h>
#include <stdlib.h>
#include "sopt_ran.h"
#include "sopt_error.h"
Functions
double sopt_ran_gasdev2 (int idum)
double sopt_ran_ran2 (int idum)
int sopt_ran_knuthshuffle (int *perm, int nperm, int N, int seed)
Detailed Description
Functionality to generate random deviates.
Definition in file sopt_ran.c.
Function Documentation
double sopt_ran_gasdev2 (int idum)
Generate sample from Gaussian distribution of mean 0 and standard deviation 1 given seed. (Using double precision.)
Parameters
[in] idum Seed.
Return values
ran_dp Generated Gaussian deviate.
Todo:
[JDM] Test generation of Gaussian deviate (then remove warning comment).
Note
Gaussian deviate inpsired from gasdev (Num Rec 1992, chap 7.3), the only difference is the use of RAN2 instead of RAN1.
This routine calls sopt_ran_ran2 and so changes the state of the random generator.
Warning
This C implementation has been copied from a Fortran version and has not yet been tested!
Must inialise sopt_ran_ran2 first with a negative seed first and then subsequently call with the identical magnitude positive seed, i.e. if seed>0, initialise sopt_ran_ran2 with -seed and then call with seed.
Author
Numerical recipes
Definition at line 38 of file sopt_ran.c.
References sopt_ran_ran2().
Referenced by main().
int sopt_ran_knuthshuffle (int * perm, int nperm, int N, int seed)
Knuth shuffle to generate random permutation of integers.
Parameters
[out] perm Array of length nperm of random permutations of integers from 0, N-1 (space must be allocated by calling routine).
[in] nperm Number of permutated integers to generate.
[in] N Number of integers to consider when generating the random permutation.
[in] seed Seed for random number generator.
Return values
error Zero indicates no errors occured.
Note
This routine calls sopt_ran_ran2 and so changes the state of the random generator.
Authors
Jason McEwen
Definition at line 143 of file sopt_ran.c.
References SOPT_ERROR_GENERIC(), SOPT_ERROR_MEM_ALLOC_CHECK(), and sopt_ran_ran2().
Referenced by main().
double sopt_ran_ran2 (int idum)
Generate uniform deviate in range [0,1) given seed. (Using double precision.)
Parameters
[in] idum Seed.
Return values
ran_dp Generated uniform deviate.
Note
Uniform deviate (Num rec 1992, chap 7.1), original routine said to be 'perfect'.
Long period (> 2 × 1018) random number generator of L’Ecuyer with Bays-Durham shuffle and added safeguards. Returns a uniform random deviate between 0.0 and 1.0 (exclusive of the endpoint values). Call with idum a negative integer to initialize; thereafter, do not alter idum between successive deviates in a sequence. RNMX should approximate the largest floating value that is less than 1.
Warning
Must inialise with a negative seed and then subsequently call with the identical magnitude positive seed, i.e. if seed>0, initialise with -seed and then call with seed.
Author
Numerical recipes
Definition at line 90 of file sopt_ran.c.
Referenced by sopt_ran_gasdev2(), and sopt_ran_knuthshuffle().