src/c/sopt_tv.c File Reference
sopt_tv.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <complex.h>
#include <math.h>
#include <cblas.h>
#include "sopt_utility.h"
#include "sopt_error.h"
#include "sopt_tv.h"
Defines
#define min(a, b) (a<b?a:b)
#define max(a, b) (a<b?b:a)
Functions
void sopt_tv_solver (void *xsol, int nx1, int nx2, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, void *y, int ny, sopt_tv_param param)
void sopt_tv_sdmm (void *xsol, int nx1, int nx2, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, void *y, int ny, double *wt_dx, double *wt_dy, sopt_tv_sdmmparam param)
void sopt_tv_rwsdmm (void *xsol, int nx1, int nx2, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, void *y, int ny, sopt_tv_sdmmparam paramtv, sopt_tv_rwparam paramrwtv)
Define Documentation
#define max (a, b) (a<b?b:a)
Definition at line 20 of file sopt_tv.c.
Referenced by sopt_tv_rwsdmm().
#define min (a, b) (a<b?a:b)
Definition at line 19 of file sopt_tv.c.
Referenced by sopt_tv_sdmm().
Function Documentation
void sopt_tv_rwsdmm (void * xsol, int nx1, int nx2, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, void * y, int ny, sopt_tv_sdmmparam paramtv, sopt_tv_rwparam paramrwtv)
Reweighted L1 minimization function that uses an homotopy continuation method to approximate the L0 norm of the magnitude of the gradient. It solves at each iteration the following problem::
where is the diagonal weight matrix, is the measurement operator, is a noise tolerance, is the measurement vector and is a diagonal weight matrix that changes at every iteration. The solution is denoted .
Note:
It uses the sdmm algorithm to solve the weighted TV problem. The solver can be used to solve the weighted problem, as written, or the un-weighted problem by setting the weight vectors, wt_dx and wt_dy, both to one.
Parameters:
[in,out] xsol Solution (). It stores the initial solution, which should be set as an input to the function, and it is modified when the finall solution is found.
[in] nx1 Dimension of the signal in the first dimension().
[in] nx2 Dimension of the signal in the first dimension().
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to measurement operator .
[in] At Pointer to the adjoint of the measurement operator .
[in] At_data Data structure associated to the adjoint of the measurement operator .
[in] y Measurement vector ().
[in] ny Dimension of measurement vector, i.e. number of measurements ().
[in] paramtv Data structure with the parameters for the TV sdmm solver (including).
[in] paramrwtv Data structure with the parameters for the reweighted TV solver.
Definition at line 818 of file sopt_tv.c.
References sopt_tv_rwparam::init_sol, max, sopt_tv_rwparam::max_iter, sopt_tv_sdmmparam::real_data, sopt_tv_rwparam::rel_var, sopt_tv_rwparam::sigma, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_tv_sdmm(), sopt_utility_gradientc(), sopt_utility_gradientr(), sopt_utility_projposc(), sopt_utility_projposr(), and sopt_tv_rwparam::verbose.
void sopt_tv_sdmm (void * xsol, int nx1, int nx2, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, void * y, int ny, double * wt_dx, double * wt_dy, sopt_tv_sdmmparam param)
This function solves the problem:
where is the measurement operator, is a noise tolerance and is the measurement vector. We represent the solution image by the vector , where .
Parameters:
[in,out] xsol Solution (). It stores the initial solution, which should be set as an input to the function, and it is modified when the finall solution is found.
[in] nx1 Dimension of the signal in the first dimension().
[in] nx2 Dimension of the signal in the first dimension().
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to measurement operator .
[in] At Pointer to the adjoint of the measurement operator .
[in] At_data Data structure associated to the adjoint of the measurement operator .
[in] y Measurement vector ().
[in] ny Dimension of measurement vector, i.e. number of measurements ().
[in] wt_dx Weight vector in x direction. Dimension: nx.
[in] wt_dy Weight vector in y direction. Dimension: nx.
[in] param Data structure with the parameters of the optimization (including).
Definition at line 338 of file sopt_tv.c.
References sopt_tv_sdmmparam::cg_max_iter, sopt_tv_sdmmparam::cg_tol, sopt_tv_sdmmparam::epsilon, sopt_tv_sdmmparam::epsilon_tol, sopt_tv_sdmmparam::gamma, sopt_tv_sdmmparam::max_iter, min, sopt_tv_sdmmparam::paramtv, sopt_tv_sdmmparam::real_data, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_prox_wtv(), sopt_utility_cgsolc(), sopt_utility_cgsolr(), sopt_utility_projposc(), sopt_utility_projposr(), sopt_utility_wtvnormc(), sopt_utility_wtvnormr(), and sopt_tv_sdmmparam::verbose.
Referenced by sopt_tv_rwsdmm().
void sopt_tv_solver (void * xsol, int nx1, int nx2, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, void * y, int ny, sopt_tv_param param)
This function solves the problem:
where is the measurement operator, is a noise tolerance and is the measurement vector. We represent the solution image by the vector , where .
Parameters:
[in,out] xsol Solution (). It stores the initial solution, which should be set as an input to the function, and it is modified when the finall solution is found.
[in] nx1 Dimension of the signal in the first dimension().
[in] nx2 Dimension of the signal in the first dimension().
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to measurement operator .
[in] At Pointer to the adjoint of the measurement operator .
[in] At_data Data structure associated to the adjoint of the measurement operator .
[in] y Measurement vector ().
[in] ny Dimension of measurement vector, i.e. number of measurements ().
[in] param Data structure with the parameters of the optimization (including).
Definition at line 50 of file sopt_tv.c.
References sopt_tv_param::epsilon, sopt_tv_param::gamma, sopt_tv_param::max_iter, sopt_tv_param::paraml2b, sopt_tv_param::paramtv, sopt_tv_param::real_meas, sopt_tv_param::real_out, sopt_tv_param::rel_obj, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_prox_l2b(), sopt_prox_tv(), sopt_utility_tvnormc(), sopt_utility_tvnormr(), and sopt_tv_param::verbose.
Referenced by main().