src/c/sopt_l2.c File Reference
sopt_l2.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <complex.h>
#include <math.h>
#include <cblas.h>
#include "sopt_utility.h"
#include "sopt_error.h"
#include "sopt_l2.h"
Functions
void sopt_l2_solver (void *xsol, int nx, void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data, void(*Psi)(void *out, void *in, void **data), void **Psi_data, void(*Psit)(void *out, void *in, void **data), void **Psit_data, int nr, void *y, int ny, double *weights, sopt_wl2_param param)
Function Documentation
void sopt_l2_solver (void * xsol, int nx, void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data, void(*)(void *out, void *in, void **data) Psi, void ** Psi_data, void(*)(void *out, void *in, void **data) Psit, void ** Psit_data, int nr, void * y, int ny, double * weights, sopt_wl2_param param)
This function solves the problem:
where is the sparsifying operator, is the diagonal weight matrix, is the measurement operator, is a noise tolerance and is the measurement vector. The solution is denoted .
Note:
The solver can be used to solve the analysis based problem, as written, or the synthesis based problem by mapping and , where is the identity matrix.
Parameters:
[in,out] xsol Solution (). It stores the initial solution, which should be set as an input to the function, and it is modified when the finall solution is found.
[in] nx Dimension of the signal ().
[in] A Pointer to the measurement operator .
[in] A_data Data structure associated to measurement operator .
[in] At Pointer to the adjoint of the measurement operator .
[in] At_data Data structure associated to the adjoint of the measurement operator .
[in] Psi Pointer to the synthesis sparsity operator .
[in] Psi_data Data structure associated to the synthesis sparsity operator .
[in] Psit Pointer to the analysis sparsity operator .
[in] Psit_data Data structure associated to the analysis sparisty operator .
[in] nr Dimension of the signal in the representation domain ().
[in] y Measurement vector ().
[in] ny Dimension of measurement vector, i.e. number of measurements ().
[in] weights Weights for the weighted L1 problem. Vector storing the main diagonal of .
[in] param Data structure with the parameters of the optimization (including).
Definition at line 72 of file sopt_l2.c.
References sopt_wl2_param::epsilon, sopt_wl2_param::gamma, sopt_wl2_param::max_iter, sopt_wl2_param::paraml2b, sopt_wl2_param::paramwl2, sopt_wl2_param::real_meas, sopt_wl2_param::real_out, sopt_wl2_param::rel_obj, SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_prox_l2b(), sopt_prox_wl2(), sopt_utility_sql2normc(), sopt_utility_sql2normr(), and sopt_wl2_param::verbose.