src/c/sopt_demo2.c File Reference
sopt_demo2.c File Reference
#include "sopt_config.h"
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <fftw3.h>
#include <math.h>
#include <assert.h>
#include <time.h>
#include "sopt_utility.h"
#include "sopt_error.h"
#include "sopt_prox.h"
#include "sopt_ran.h"
#include "sopt_meas.h"
#include "sopt_tv.h"
#include "sopt_l1.h"
#include "sopt_wavelet.h"
#include "sopt_sara.h"
#include "sopt_sparsemat.h"
#include "sopt_image.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 35 of file sopt_demo2.c.
References sopt_l1_param::epsilon, sopt_tv_param::epsilon, sopt_l1_param::gamma, sopt_tv_param::gamma, sopt_l1_rwparam::init_sol, sopt_l1_param::max_iter, sopt_tv_param::max_iter, sopt_prox_l1param::max_iter, sopt_prox_tvparam::max_iter, sopt_prox_l2bparam::max_iter, sopt_l1_rwparam::max_iter, sopt_sara_param::ndict, sopt_prox_l1param::nu, sopt_prox_l2bparam::nu, sopt_l1_param::paraml1, sopt_l1_param::paraml2b, sopt_tv_param::paraml2b, sopt_tv_param::paramtv, sopt_prox_l1param::pos, sopt_prox_l2bparam::pos, sopt_sara_param::real, sopt_prox_l2bparam::real, sopt_l1_param::real_meas, sopt_tv_param::real_meas, sopt_l1_param::real_out, sopt_tv_param::real_out, sopt_l1_param::rel_obj, sopt_tv_param::rel_obj, sopt_prox_l1param::rel_obj, sopt_prox_tvparam::rel_obj, sopt_l1_rwparam::rel_var, sopt_l1_rwparam::sigma, SOPT_ERROR_GENERIC(), SOPT_ERROR_MEM_ALLOC_CHECK(), sopt_l1_rwmin(), sopt_l1_solver(), sopt_ran_gasdev2(), sopt_ran_knuthshuffle(), sopt_sara_analysisop(), sopt_sara_free(), sopt_sara_initop(), sopt_sara_synthesisop(), sopt_tv_solver(), SOPT_WAVELET_DB1, SOPT_WAVELET_DB2, SOPT_WAVELET_DB3, SOPT_WAVELET_DB4, SOPT_WAVELET_DB5, SOPT_WAVELET_DB6, SOPT_WAVELET_DB7, SOPT_WAVELET_DB8, spot_image_tiff_read(), spot_image_tiff_write(), sopt_prox_l1param::tight, sopt_prox_l2bparam::tight, sopt_prox_l2bparam::tol, sopt_l1_param::verbose, sopt_tv_param::verbose, sopt_prox_l1param::verbose, sopt_prox_tvparam::verbose, sopt_prox_l2bparam::verbose, and sopt_l1_rwparam::verbose.