src/c/sopt_sparsemat.c File Reference
sopt_sparsemat.c File Reference
#include "sopt_config.h"
#include <stdlib.h>
#include "sopt_sparsemat.h"
#include "sopt_error.h"
Functions
void sopt_sparsemat_free (sopt_sparsemat *mat)
void sopt_sparsemat_explictmat (double **A, sopt_sparsemat *S)
void sopt_sparsemat_fwd_real (double *y, double *x, sopt_sparsemat *A)
void sopt_sparsemat_adj_real (double *y, double *x, sopt_sparsemat *A)
void sopt_sparsemat_fwd_complex (complex double *y, complex double *x, sopt_sparsemat *A)
void sopt_sparsemat_adj_complex (complex double *y, complex double *x, sopt_sparsemat *A)
Detailed Description
Functionality to perform operations with sparse matrices.
Definition in file sopt_sparsemat.c.
Function Documentation
void sopt_sparsemat_adj_complex (complex double * y, complex double * x, sopt_sparsemat * A)
Multiple a complex vector by the adjoint of a real sparse matrix, i.e. compute , where is the Hermitian operator.
Parameters
[out] y Ouput vector of length ncols.
[in] x Input vector of length nrows.
[in] A Sparse matrix (passed by reference).
Note
Space for the output vector must be allocated by the calling routine.
Authors
Jason McEwen
Definition at line 156 of file sopt_sparsemat.c.
References sopt_sparsemat::colptr, sopt_sparsemat::cvals, sopt_sparsemat::ncols, and sopt_sparsemat::rowind.
Referenced by sopt_meas_sparsematadjc().
void sopt_sparsemat_adj_real (double * y, double * x, sopt_sparsemat * A)
Multiply a real vector by the adjoint of a real sparse matrix, i.e. compute , where is the Hermitian operator.
Parameters
[out] y Ouput vector of length ncols.
[in] x Input vector of length nrows.
[in] A Sparse matrix (passed by reference).
Note
Space for the output vector must be allocated by the calling routine.
Authors
Jason McEwen
Definition at line 102 of file sopt_sparsemat.c.
References sopt_sparsemat::colptr, sopt_sparsemat::ncols, sopt_sparsemat::rowind, and sopt_sparsemat::vals.
Referenced by sopt_meas_sparsematadjr().
void sopt_sparsemat_explictmat (double ** A, sopt_sparsemat * S)
Compute explicit representation of a sparse matrix.
Parameters
[out] A Explicit matrix representation of sparse matrix S. The matrix A is stored in column-major order, i.e. can be accessed as A[col_index * nrows + row_index].
[in] S Sparse matrix to representation explicitly (passed by reference).
Note
Space for the output matrix A is allocated herein and must be freed by the calling routine.
Authors
Jason McEwen
Definition at line 46 of file sopt_sparsemat.c.
References sopt_sparsemat::colptr, sopt_sparsemat::ncols, sopt_sparsemat::nrows, sopt_sparsemat::rowind, SOPT_ERROR_MEM_ALLOC_CHECK(), and sopt_sparsemat::vals.
void sopt_sparsemat_free (sopt_sparsemat * mat)
Free all memory used to store a spare matrix.
Parameters
[in] mat Sparse matrix to free.
Authors
Jason McEwen
Definition at line 19 of file sopt_sparsemat.c.
References sopt_sparsemat::colptr, sopt_sparsemat::cvals, sopt_sparsemat::ncols, sopt_sparsemat::nrows, sopt_sparsemat::nvals, sopt_sparsemat::rowind, and sopt_sparsemat::vals.
void sopt_sparsemat_fwd_complex (complex double * y, complex double * x, sopt_sparsemat * A)
Multiply a complex vector by a real sparse matrix, i.e. compute .
Parameters
[out] y Ouput vector of length nrows.
[in] x Input vector of length ncols.
[in] A Sparse matrix (passed by reference).
Note
Space for the output vector must be allocated by the calling routine.
Authors
Jason McEwen
Definition at line 128 of file sopt_sparsemat.c.
References sopt_sparsemat::colptr, sopt_sparsemat::cvals, sopt_sparsemat::ncols, sopt_sparsemat::nrows, and sopt_sparsemat::rowind.
Referenced by sopt_meas_sparsematc().
void sopt_sparsemat_fwd_real (double * y, double * x, sopt_sparsemat * A)
Multiple a real vector by a real sparse matrix, i.e. compute .
Parameters
[out] y Ouput vector of length nrows.
[in] x Input vector of length ncols.
[in] A Sparse matrix (passed by reference).
Note
Space for the output vector must be allocated by the calling routine.
Authors
Jason McEwen
Definition at line 75 of file sopt_sparsemat.c.
References sopt_sparsemat::colptr, sopt_sparsemat::ncols, sopt_sparsemat::nrows, sopt_sparsemat::rowind, and sopt_sparsemat::vals.
Referenced by sopt_meas_sparsematr().