get_filename_component(Sopt_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
message(STATUS "Linking to sopt package in ${Sopt_CMAKE_DIR}")
set(Sopt_INCLUDE_DIRS "@ALL_INCLUDE_DIRS@")
if(NOT TARGET libsopt AND EXISTS "${Sopt_CMAKE_DIR}/SoptCTargets.cmake")
  include("${Sopt_CMAKE_DIR}/SoptCTargets.cmake")
endif()
if(NOT TARGET sopt AND EXISTS "${Sopt_CMAKE_DIR}/SoptCPPTargets.cmake")
  include("${Sopt_CMAKE_DIR}/SoptCPPTargets.cmake")
endif()

unset(Sopt_LIBRARIES)
if(TARGET sopt)
  list(APPEND Sopt_LIBRARIES sopt)
  set(Sopt_CPP_LIBRARY sopt)
  if(NOT GreatCMakeCookOff_FOUND)
    include(${Sopt_CMAKE_DIR}/LookUp-GreatCMakeCookOff)
  endif()
  include(PackageLookUp)
  lookup_package(Eigen3 REQUIRED)
  if(Eigen3_BUILT_AS_EXTERNAL_PROJECT)
    include_directories(${EIGEN3_INCLUDE_DIR})
  endif()
  if(NOT "@logging@" STREQUAL "")
    lookup_package(spdlog REQUIRED)
    if(spdlog_BUILT_AS_EXTERNAL_PROJECT)
      include_directories(${SPDLOG_INCLUDE_DIR})
    endif()
  endif()
endif()
if(TARGET libsopt)
  list(APPEND Sopt_LIBRARIES libsopt)
  set(Sopt_C_LIBRARY libsopt)
endif()
set(Sopt_ABOUT_EXECUTABLE sopt_about)
